### PR TITLE
Adding locale.fr.js

### PR DESCRIPTION
**Pull request by Falafel65**
Yay, French !

I don't know if it's the right way to add translation, but anyway, here is the french one.

### CODE REVIEW

**Comment by Falafel65** [comment]
Noooes I failed again at adding things to Mavo, this is obviously a plugin T_T
Closing here, opening at the plugins part.

**Comment by LeaVerou** [comment]
Looks good apart from that!

**Comment by LeaVerou** [comment]
Are you going to add it to plugins?

You can follow the Greek one as an example. Name it `mavo-locale-fr.js`.

**Comment by Falafel65** [comment]
I intended to, then my Internet crashed 😞 

I made a repo (https://github.com/Falafel65/mavo-locale-fr), I was about to adding it via plugins.mavo.io, is that ok ?

**Comment by LeaVerou** [comment]
Yes, that works great!

**Pull request closed without merging**
