### PR TITLE
Negative inputs to `duration` now produce negative time outputs

### PR DESCRIPTION
**Pull request by BarishNamazov**
Solves the main issue agreed on: https://github.com/mavoweb/mavo/issues/925
For 0 input, still returns `0 ms`.

### CODE REVIEW

**Review by LeaVerou — APPROVED** [review]
LGTM. 

Note that `===` will not work if `ms` comes directly from a property (as it will be an object), though I see it's used above too, so I'm not gonna block this for that, but `==` would work for both cases. 

Before we merge, could you add some tests too? This is the tests repo: https://github.com/mavoweb/test

**Comment by BarishNamazov** [comment]
Good call! There's something interesting with negative numbers I just noticed (I had the feeling of breaking some math rules while implementing this, but just couldn't get my head around it back then). With positive numbers, we round it down (e.g., `2 hours 51 minutes` become `2 hours`), but rounding down mathematically works differently for negative numbers (`-2 hours 5 minutes` become `-3 hours`). Which one do you think makes more sense?

I don't have a strong preference since it's rounding anyway, but I feel like to keep it consistent with positive numbers (though not mathematically), like `-2 hours 51 minutes` becoming `-2 hours` makes more sense to me. I caught this when I was writing tests:

image

(note that this is the part of the implementation that happens in the first if statement in the function, not affected by this PR)

What do you think? Should I do that change and push it here? Or we should stick to the mathematical version (both are easy to implement: doing it like positives needs you to convert to abs value and then convert back to negative, while other one doesn't require any special treatment)?

**Comment by LeaVerou** [comment]
I agree with your intuition: the rounding should operate on the absolute value, instead of doing proper mathematical rounding, since I suspect in most cases this will just be caused by people subtracting in the wrong order so it will be confusing if they get a different result once they fix the order.

**Comment by BarishNamazov** [comment]
should be done now!

**Comment by LeaVerou** [comment]
Great work, merged! 
In the future, please include phrases like "closes #925" in one of your commit messages so that it automatically closes the relevant issue, see https://github.blog/2013-01-22-closing-issues-via-commit-messages/

**Pull request merged**
