### PR TITLE
Fix for #469

### PR DESCRIPTION
**Pull request by DmitrySharabin**
Retain button order in the bar when the relative syntax is used.

Added the corresponding test to the test suite.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi Dmitry,

Thank you so much for working on this!!

It may very well be because I'm really sleepy, but I can't understand how this change works. Could you explain and add a comment in the code too?

**Comment by DmitrySharabin** [comment]
Let me explain it here first, and then we'll decide what comments to add to the code.

After detecting that we use the relative syntax, we get a set of buttons that will be available in the bar (lines 203 through 210). Their order is determined by the order of corresponding properties in the source code since the `all` variable has value `Object.keys(_.controls)` (see line 188).

But for some buttons, we need to change their order to retain the one specified by a developer. This order is provided in the `ids` variable, but since we haven't changed its value, there might be values that are not acceptable as a button's `id` (e.g., `foo`) or have already been taken into account in the previous step (were kept or dropped).

So in line 212, we drop from `ids` all the values that are not in the set of buttons in the bar (by retaining the order of the kept ones).

Then, in the full set of buttons in the bar, we “mark” positions of the buttons specified by a developer (by replacing them with `undefined`—it could be any distinguishable value)—line 214. And in the next step (line 215), we fill in “the gaps” (the marked positions) with the buttons in the order specified by a developer.

I am not sure that my explanation is clear, so I made a sketch with an example. Please, have a look: 
https://excalidraw.com/#json=5753373420683264,U9lDYzx9SaRIzxK0sGmuTQ

My drawing skills might drive you crazy. lol

**Comment by DmitrySharabin** [comment]
I think I need to think it over a bit more—too many extra steps. Let's see whether I could find a more intelligent solution.

**Comment by LeaVerou** [comment]
Wow, I love using a sketch to illustrate! I'm still a bit confused, but I sort of get it better now.
And yes, I think there could be a better solution (using undefined like that is a bit of a hack), but if you can't find one and you're confident that this one fixes the bug and doesn't introduce regressions, I could merge it.

**Comment by karger** [comment]
I'm having trouble understanding the algorithm and the sketch so I was hoping to understand how it differs from the following simple one:

- start with default buttons
- delete all no-foo buttons
- move all specified buttons to the front, in order specified

I guess an alternative to (3) would be to move them to the back, but I can't think why that would be better (or worse).

I guess one other option to promote flexibility would be to add a "rest" keyword that indicates where all the unspecified buttons should be, so you could say e.g. 
buttons = "with import rest export"

**Comment by DmitrySharabin** [comment]
David, will you please have a look at the refactored code?  I committed it recently. I’ll be grateful for any feedback.

**Comment by karger** [comment]
Dmity I've looked and couldn't immediately make sense of the various position calculations and sorting that you used.  Does this design stem from a goal of being very efficient?   Because given the small number of buttons I would instead incline towards something less efficient but more transparent, such as
- from the default list, remove all buttons in the "with" list (ignoring no- prefix)
- attach at front (or end) all the buttons added in "with", in order specified.

Or perhaps your goal is not efficiency but to achieve a more appropriate ordering.  If so I'm not sure what is the characteristic of the ordering you want to achieve.

**Comment by DmitrySharabin** [comment]
David, thank you so much for your feedback. I appreciate it.

You are right, I complicated the solution way too much. My main goal was to reuse the existing code as much as I can and try to keep the current order of controls in the default set and swap only some of them to retain the order of controls specified by a user. Unfortunately, I failed. But I find my attempts extremely useful. Maybe not for Mavo, but definitely for me. :)

I totally agree I must choose a more transparent way to fix the issue.

> Or perhaps your goal is not efficiency but to achieve a more appropriate ordering. If so I'm not sure what is the characteristic of the ordering you want to achieve.

I really like the idea of adding the `rest` keyword. I believe it would cover all the cases we try to cover now. Thank you.

**Comment by karger** [comment]
minor thought, but perhaps instead of "rest" (which is confusing in an http context) "others" would be a better catch-all keyword.

**Pull request closed without merging**
