### PR TITLE
Run eslint on `npm test`

### PR DESCRIPTION
**Pull request by henrahmagix**
To maybe help with contributing?

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hey, thanks for contributing!
There is a testsuite, though it's a separate website & repo: https://github.com/mavoweb/test
Sadly, it's lacking documentation on how someone can add tests and check if their changes break something.
It doesn't seem appropriate to put code style verification in the place of tests. Also, are you sure that running ESLint like that doesn't check the js files in `dist/` too? We only want the ones in `src/` checked...

**Comment by henrahmagix** [comment]
>There is a testsuite, though it's a separate website & repo

Oh cool, I didn't see that, thanks! I'm looking forward to giving that a good read to understand how you're testing it: at first glance it seems new to me, I'm excited! SIWL (soon I will learn) Service Workers 🎉

>are you sure that running ESLint like that doesn't check the js files in `dist/` too?

Yeah, the `.eslintignore` takes care of that. I was thinking of targeting only `src/`, but targeting everything and ignoring some would capture more files, like `gulpfile.js`, and any that are added later.

>It doesn't seem appropriate to put code style verification in the place of tests.

Absolutely: code style isn't really testing on its own. But I think simply allowing eslint to be used more easily by more contributors, since there's already a config file for it, is a worthwhile addition, albeit small in the grand scheme of things :) Perhaps saves time on future PRs to this repo if you want to enforce the code style?

**Comment by mycaule** [comment]
Sindre Sohrus is doing that systematically on his packages : lint with `xo` and run tests with `ava`.
I think it is a very good practice.
https://github.com/sindresorhus/element-ready/blob/master/package.json#L16

**Comment by LeaVerou** [comment]
Instead of assigning ESLint on `npm test` ideally I should set up Travis to check if PRs pass ESLint so that both I and contributors know before merging. 

Since it's not really tests, I'm gonna close this, sorry about that @henrahmagix, I hope it does not deter you from future contributions!

**Comment by henrahmagix** [comment]
No worries at all - thanks for reviewing :)

**Comment by LeaVerou** [comment]
Glad to hear that! 
Btw, if you want to help with the Travis config, it would really help speed this up :)

**Pull request closed without merging**
