### PR TITLE
Fix for the `intersection()` function

### PR DESCRIPTION
**Pull request by DmitrySharabin**

### CODE REVIEW

**Review by LeaVerou — CHANGES_REQUESTED** [review]
Dropping proxies fixes it, but also means we lose the reference back to the property the items came from. We should use `val()` when comparing items (ideally with some way to make sure we don't do this multiple times per item).

**Comment by DmitrySharabin** [comment]
> Dropping proxies fixes it, but also means we lose the reference back to the property the items came from.

Thank you very much for pointing this out. I haven't thought about it in advance. I tried another approach in the new commit. Please have a look when you have a spare cycle.

**Review by lewisushindi — COMMENTED** [review]
looks fine according to me

**Review by LeaVerou — APPROVED** [review]
LGTM!

**Pull request merged**
