### PR TITLE
improved .eslintrc file with globals and indentation rules

### PR DESCRIPTION
**Pull request by valterkraemer**
These additions removed most of the invalid errors eslint gave me.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi there,

Thanks for contributing. Where were you getting errors from eslint? I don't get any. Perhaps you were running it against the files in `dist/`?

**Comment by valterkraemer** [comment]
I investigated a bit. The reason was that I have another .eslintrc file higher up in the folder hierarchy with different rules (in this case `"extends": "eslint:recommended"`) that were inherited to the Mavo project.

**Comment by henrahmagix** [comment]
Adding `"root": true` will ensure eslint never combines with a developer's own config, say in their home directory (usually an ancestor directory to repos): https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy

**Comment by henrahmagix** [comment]
Oh, just realised and read that configs in `~/.eslintrc.*` are ignored if project- or folder-level configs are found. That's a nice, somewhat expected feature. `"root": true` may still prove useful, but otherwise please ignore me =D

**Pull request closed without merging**
